<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>new_backend</RootNamespace>
  </PropertyGroup>

  <!-- ADD THIS SECTION -->
  <ItemGroup>
    <Compile Remove="console\**" />
    <EmbeddedResource Remove="console\**" />
    <None Remove="console\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.9" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="MongoDB.Bson" Version="3.5.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
    <PackageReference Include="RazorEngineCore" Version="2024.4.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

</Project>